apiVersion: v1
kind: Service
metadata:
  name: k8s-tool-agent
  labels:
    app.kubernetes.io/name: k8s-tool
    app.kubernetes.io/component: agent
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: k8s-tool
    app.kubernetes.io/component: agent
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-tool-server
  labels:
    app.kubernetes.io/name: k8s-tool
    app.kubernetes.io/component: server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: k8s-tool
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
